### ISSUE TITLE
Problem with FindProtobuf

### ISSUE THREAD

**Issue by al-rigazzi** [dmlc/ps-lite#103]
Hi,

CMake gives me an error when I try to compile MXNet using ps-lite, as the Protobuf libraries are not exported to PARENT. I think I tracked the problem and it should be in [these lines.](https://github.com/dmlc/ps-lite/blob/acdb698fa3bb80929ef83bb37c705f025e119b82/CMakeLists.txt#L57-L58)
Basically, FindProtobuf exports PROTOBUF_LIBRARY ([see here](https://cmake.org/cmake/help/v3.0/module/FindProtobuf.html)), whereas the lines look for Protobuf_LIBRARY. Is anyone else having a similar problem?

**Comment by al-rigazzi** [comment]
So, it seems a problem with the FindProtobuf module, which changed the name of the variable after CMake version 3.6.

**Comment by eric-haibin-lin** [comment]
cmake was improved in (#170)

**Comment by leezu** [comment]
@al-rigazzi I didn't check if #170 addressed this particular issue. Please report if you still face this issue and we can reopen.
