### ISSUE TITLE
Implement fp16 support for the KV-Store

### ISSUE THREAD

**Issue by b0noI** [dmlc/ps-lite#127]
Currently MXNet can be used in distributed mode only with fp32

**Comment by ejdaly** [comment]
+1 this would be a super improvement for distributed mode

**Comment by mli** [comment]
Thanks for asking. The AWS team is working on it.

**Comment by qiaohaijun** [comment]
great

**Comment by anirudhacharya** [comment]
shouldn't this issue be tracked in the mxnet repo? if kv-store is to support fp16, most of the changes will be made there.

**Comment by eric-haibin-lin** [comment]
fp16 support has been added to mxnet.
