### ISSUE TITLE
Non Zero-Copy Implementation in ZPull

### ISSUE THREAD

**Issue by ymjiang** [dmlc/ps-lite#146]
https://github.com/dmlc/ps-lite/blob/f50108bcd4e7dd96be0a1596eb2b278f766306ad/include/ps/kv_app.h#L591-L598

While `ZPull` claims to be zero-copy, the `PullImpl` that `ZPull` calls actually involves memcpy, which can hurt performance. Is it possible to remove them?

@mli @CodingCat

**Comment by eric-haibin-lin** [comment]
@ymjiang did you figure it out?

**Comment by ymjiang** [comment]
@eric-haibin-lin Hi, finally I realize this is impossible if we keep using ZeroMQ. Because when receiving a message you need to first declare a ZMQ buffer (whose address cannot be controlled), so on receiving you will have to copy the data from the ZMQ buffer to your desired address.  

However, if we use RDMA rather than ZMQ, there is a chance to do in-place pull, i.e., a real zero-copy pull.

**Comment by eric-haibin-lin** [comment]
Look forward to the RDMA PR :)

**Comment by ymjiang** [comment]
@eric-haibin-lin Hi, we just open source our RDMA patch. See https://github.com/dmlc/ps-lite/pull/124 for details :)
