### ISSUE TITLE
Does server replication works?

### ISSUE THREAD

**Issue by YongCHN** [dmlc/ps-lite#15]
I noticed in class Executor member variable **num_replicas_** is assigned as 0 by default. But in the implementation file there is no place assigning new values to this variable again. But in executor.cc line 358, this variable is checked to see whether enable the server replication or not, which means under this context the server replication feature never works. 

Is the server replication feature provided by ps-lite? Thanks.

**Comment by mli** [comment]
the short answer is no.

there is still debate on how to achieve fault tolerance in practice, checkpoint or chain replica. so i leave it empty here until it is actually needed
