### ISSUE TITLE
Is there an implementation of matrix transport based on ps-lite?

### ISSUE THREAD

**Issue by hbsun2113** [dmlc/ps-lite#156]
For a k-v pair, the v is a matrix. In other words, it is not necessary to assign a key to every element in the matrix. Is there an implementation of matrix transport based on ps-lite?

**Comment by eric-haibin-lin** [comment]
in ps-lite, v is already a matrix. what do you mean by matrix transport?

**Comment by hbsun2113** [comment]
> in ps-lite, v is already a matrix. what do you mean by matrix transport?

If a v is a matrix, then the matrix will be stored on only one server. I want the matrix to be stored on multi servers. I think it will reduce the communication cost.

**Comment by eric-haibin-lin** [comment]
You can control the granularity, by splitting a matrix into multiple keys and spreading these keys to multiple servers

**Comment by hbsun2113** [comment]
> You can control the granularity, by splitting a matrix into multiple keys and spreading these keys to multiple servers

Yeap! But I think ps-lite should provide the API for the general case like load-balance.
