### ISSUE TITLE
Makefile:32: recipe for target 'lint' failed

### ISSUE THREAD

**Issue by hbsun2113** [dmlc/ps-lite#172]
I run the command `make lint`, but failed: 
"Makefile:32: recipe for target 'lint' failed"
"make: *** [lint] Error 1".

The figure shows:
![image](https://user-images.githubusercontent.com/27994442/76163976-c6ad1d00-6185-11ea-9566-e80119049ecb.png)

Can you tell me how to check the code by `lint`?
@eric-haibin-lin @leezu

**Comment by eric-haibin-lin** [comment]
did u figure it out?

**Comment by hbsun2113** [comment]
@eric-haibin-lin Yes, python2 works well , while python3 failed.

**Comment by ThiagoPanini** [comment]
I have the same problem here. Does anyone knows how to fix this?
