### ISSUE TITLE
Is there an example script showing how to run on cluster ?

### ISSUE THREAD

**Issue by chenghuige** [dmlc/ps-lite#18]
Like rabit_mpi.py 
Thanks!

**Comment by chenghuige** [comment]
find it... from paramter server

**Comment by mli** [comment]
one example http://wormhole.readthedocs.org/en/latest/common/build.html#setup-an-ec2-cluster-from-scratch

it also runs on other platform such as yarn

**Comment by chenghuige** [comment]
Thanks, mu. I tried   
tracker/dmlc_local.py -n 2 -s 1 bin/linear.dmlc learn/linear/guide/demo.conf
2015-09-23 11:49:14,558 INFO start listen on 10.48.118.42:9091

It only print one line and terminated, what might be the problem?

**Comment by mli** [comment]
probably the port is not accessible?

are you using ec2? if so, you need open the tcp port on the ec2 console

**Comment by chenghuige** [comment]
Well, just tried running locally on my local machine.

**Comment by chenghuige** [comment]
I find it due to some compile issue using HDFS=1
