### ISSUE TITLE
Handling of array values

### ISSUE THREAD

**Issue by shilad** [dmlc/ps-lite#9]
If I push a ps::Key of { 0 } with a ps::Val of { 1, 3 }, the documentation made me believe the server should be storing 0 => [ 1, 3 ]. However, it looks to be storing  0 => (1 + 3) = 4. Is this intentional?

I'm going to extend KVWorker class to handle float arrays, but I was under the impression it would work out of the box. Thanks for your advice!

**Comment by shilad** [comment]
Example program:

`c
#include "ps.h"
typedef float Val;

int CreateServerNode(int argc, char *argv[]) {
  ps::OnlineServer<Val> server(ps::IOnlineHandle<float>(), 3, 0);
  return 0;
}

int WorkerNodeMain(int argc, char *argv[]) {
  using namespace ps;
  std::vector<Key> key = {1};
  std::vector<Val> val = {1, 2, 3};
  std::vector<Val> recv_val;

  KVWorker<Val> wk;
  int ts = wk.Push(key, val);
  wk.Wait(ts);

  ts = wk.Pull(key, &recv_val);
  wk.Wait(ts);

  std::cout << "values pulled at " << MyNodeID() << ": " <<
      Blob<const Val>(recv_val) << std::endl;
  return 0;
}
`

With output:
`
values pulled at W0: [3]: 6 6 6 
`

**Comment by shilad** [comment]
After a little more poking around, I realized example_e contained a working handler for vectors. Sorry for the confusion. Perhaps the guide clarify this? I'd be happy to give you a PR on it if you think it's appropriate.

**Comment by mli** [comment]
It will be fantastic if you can update the guide:) Thanks.
